import React, { useState } from "react";
import dynamic from "next/dynamic";
import Head from "next/head";
// import { Carousel, CarouselItem, SSRProvider } from "react-bootstrap";

import {
  CarouselCard,
  CarouselHeading,
  CarouselContent,
} from "../components/Carousel";
import { FaBeer } from "react-icons/fa";
import {
  VerticalTimeline,
  VerticalTimelineElement,
} from "react-vertical-timeline-component";

const CustomCarousel = dynamic(
  async () => {
    const module = await import("../components/Carousel");
    return module.default;
  },
  { ssr: false }
);
// import {
//   Carousel,
//   CarouselCard,
//   CarouselContent,
//   CarouselHeading,
// } from "../components/Carousel";
import Navbar from "../components/Navbar";
import Sketch from "../components/p5/Sketch";

// P5 Sketches
import Snowfall from "../components/p5/sketches/Snowfall";

// Datasets
import EventData from "../utils/EventData";
import TimelineData from "../utils/TimelineData";

// CSS imports
import "react-vertical-timeline-component/style.min.css";
import Model from "../components/p5/sketches/Model";

export default function Home() {
  let [activeIndex, setActiveIndex] = useState(0);
  const handleSelect = () => {
    setActiveIndex((prev) => ++prev);
  };

  const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3, // optional, default to 1.
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2, // optional, default to 1.
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1, // optional, default to 1.
    },
  };

  return (
    <div>
      {/* Head */}
      <Head>
        <title>Seige - IEEE MUJ Tech Fest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* Body */}
      <main>
        <div className=" ">
          {/* P5 Background */}
          <div className="fixed bg-black top-0 left-0 -z-10">
            <Sketch sketch={Snowfall} />
          </div>

          {/* Navbar */}
          <Navbar background="bg-gray-700/10" blur="2xl" links={[]} />

          {/* Main Page */}
          <div className="py-40 px-6 md:px-12 bg-transparent backdrop-blur-sm z-50">
            <div className="flex flex-col lg:flex-row mx-3 lg:mx-32 my-20 gap-10 lg:gap-0">
              <div className="lg:basis-2/3 flex items-center lg:items-start">
                <div
                  id="title"
                  className=" flex flex-col items-center lg:items-start gap-10 lg:gap-2"
                >
                  <h1 className="text-9xl md:text-9xl font-bold font-orbitron text-gray-100">
                    {" "}
                    SEIGE{" "}
                  </h1>
                  <p className="text-xl md:text-2xl font-noto-sans text-center lg:text-left text-gray-600">
                    {" "}
                    Seige is the Summer Technical Fest organised by the IEEE MUJ
                    student Chapter at Manipal University Jaipur{" "}
                  </p>
                </div>
              </div>

              <div className="lg:basis-1/3 mx-auto flex flex-row justify-center items-center">
                <Sketch sketch={Model} />
              </div>
            </div>

            <div className="my-40 flex flex-row">
              <div className="hidden md:flex w-full"></div>
              <div className=" flex flex-col gap-3 md:gap-5">
                <h1 className=" text-center md:text-left text-white text-5xl font-noto-sans font-bold ">
                  Welcome to the Final Seige
                </h1>
                <p className="text-white text-center md:text-left font-noto-sans">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex
                </p>
              </div>
            </div>


            {/* Event Carousel */}
            <CustomCarousel eventData={EventData} />

            <h1 className="mx-auto my-10 text-white text-7xl font-bold text-center">
              Timeline
            </h1>
            <VerticalTimeline lineColor="white">
              {TimelineData.map((element, index) => {
                return (
                  <VerticalTimelineElement
                    className="vertical-timeline-element--work"
                    contentStyle={{
                      background: "rgb(33, 150, 243)",
                      color: "#fff",
                    }}
                    contentArrowStyle={{
                      borderRight: "7px solid  rgb(33, 150, 243)",
                    }}
                    date={element.date}
                    iconStyle={{
                      background: "rgb(33, 150, 243)",
                      color: "#fff",
                    }}
                    icon={<FaBeer />}
                  >
                    {element.events.map((eventName, eventIndex) => (
                      <div className="mb-20">
                        <h1 className="text-xl font-bold vertical-timeline-element-title">
                          {eventName}
                        </h1>
                        {/* <h4 className="vertical-timeline-element-subtitle">Miami, FL</h4> */}
                        <p>
                          {/* Creative Direction, User Experience, Visual Design, Project Management, Team Leading */}
                          {element.shortDescription[eventIndex]}
                        </p>
                      </div>
                    ))}
                  </VerticalTimelineElement>
                );
              })}
            </VerticalTimeline>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
